
services:
  zinfurn-next:
    container_name: zinfurn-next
    restart: always
    image: node:20.10.0
    ports:
      - 5000:3000 
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/zinfurn-next
    working_dir: /usr/src/zinfurn-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
