services:
  asadbek-zinfurn-next:
    container_name: asadbek-zinfurn-next
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: asadbek-zinfurn-next:latest
    ports:
      - "127.0.0.1:5000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - asadbek-zinfurn-network

networks:
  asadbek-zinfurn-network:
    driver: bridge
