export enum CommentStatus {
	ACTIVE = 'ACTIVE',
	DELETE = 'DELETE',
}

export enum CommentGroup {
	MEMBER = 'MEMBER',
	ARTICLE = 'ARTICLE',
	PROPERTY = 'PROPERTY',
	PROPERTY_QA = 'PROPERTY_QA',
	REPAIR_PROPERTY = 'REPAIR_PROPERTY',
}
